services:
  db:
    image: postgres:15-alpine
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: ri_joy_user
      POSTGRES_PASSWORD: ri_joy_password
      POSTGRES_DB: ri_joy

  localstack:
    image: localstack/localstack:3.4.0
    ports:
      - 4566:4566
    environment:
      SERVICES: s3
    env_file:
      - .env