services:
  db:
    image: postgres:15-alpine
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: ri_joy_user
      POSTGRES_PASSWORD: ri_joy_password
      POSTGRES_DB: ri_joy
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: